service: default
runtime: python37

basic_scaling:
    max_instances: 1
    idle_timeout: 10m
    
resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 5
    
entrypoint: gunicorn -b 0.0.0.0:8080 main:server

env_variables:
  PORT: 8080